baseurl: /
languageCode: en-US
title: Neil Dabholkar
disqusShortname: ''
googleAnalytics: ''
theme: hugo-sustain
permalinks:
  post: /post/:year/:month/:day/:slug
params:
  about: I'm into predictive analytics, investing, systems biology, and reading whatever I can get my hands on.
  author: Neil Dabholkar
  avatar: 0.jpg
  custom_css: []
  custom_js: []
  occupation: Quant
  social:
    Email: ndabholkar@utexas.edu
    Github: username
    LinkedIn: neil-dabholkar
    Twitter: neildabholkar
menu:
  main:
    - identifier: blog
      name: blog
      url: /post/
      weight: 100
    - identifier: projects
      name: projects
      url: /projects/
      weight: 200
    - identifier: resume
      name: resume
      url: /resume/
      weight: 300
